### ISSUE TITLE
Need to use the ACH feature in a .NET7.0 Core App

### ISSUE THREAD

**Issue by webzest** [square/web-payments-quickstart#147]
Hi,
I am able to get the ACH code to display properly and return a success in PLAID during the link-to-bank to SQUARE phase in a Sandbox, however, when I clicked CONTINUE, the code returned a "Payment Failed" error and  a "Failed to load resource: the server responded with a status of 404 ()" for the /payment page.

Can you provide some guidance as to an integration of the ACH code into a .NET7 Core Blazor app that I can use as a simple page to allow customers to pay either via a CC or a Bank transfer?

Thank you for your support.

**Comment by maxbeatty** [comment]
If you are using .NET for your server instead of the Node.js server provided in this repository, you'll need to implement a [similar endpoint](https://github.com/square/web-payments-quickstart/blob/31ef8e6ff6c3cbb5721a1339617a7e038c0f041a/server.js#L153) on your server or change the `fetch` URL [on the client](https://github.com/square/web-payments-quickstart/blob/31ef8e6ff6c3cbb5721a1339617a7e038c0f041a/public/examples/ach.html#L33-L34).

Our [developer forum](https://developer.squareup.com/forums/tag/web-payments-sdk) may be able to provide better support for your integration 😄
